### ISSUE TITLE
How fast is it to inference?

### ISSUE THREAD

**Issue by dotorl127** [maudzung/Complex-YOLOv4-Pytorch#7]
What is the total processing time from pre processing to post processing within inference?

**Comment by maudzung** [comment]
Hi @dotorl127 

I didn't measure the pre-processing time, but the forward pass time is similar to the original YOLOv4 model because I used the same input size.
There is a difference in the post-processing time, this implementation is slower than the 2D object detection task because we need to consider the rotated angle also. The IoU calculation for rotated boxes couldn't be vectorized, so it's much slower than the traditional IoU calculation.
